spring.application.name=job-service
server.port=8082
spring.cloud.compatibility-verifier.enabled=false

app.jwt.secret=a4558b80-6594-4f4f-910b-1bc2ca62dfbf

spring.data.mongodb.uri=${MONGODB_URI:your_default_mongodb_uri}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/