spring.application.name=job-service
server.port=8082

app.jwt.secret=a4558b80-6594-4f4f-910b-1bc2ca62dfbf

spring.data.mongodb.uri=mongodb+srv://huynhvanloi956_db_user:loivabin010100110001@cluster0.c40nhhu.mongodb.net/job_recruitment