spring.application.name=spring-cloud-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#config allow cors front-end
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=1800

#config apply filter to multi-service

#Auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

#Job-service (Public for get jobs)
spring.cloud.gateway.routes[1].id=job-service-public
spring.cloud.gateway.routes[1].uri=lb://job-service
spring.cloud.gateway.routes[1].predicates[0]=Method=GET
spring.cloud.gateway.routes[1].predicates[1]=Path=/api/jobs/**

spring.cloud.gateway.routes[2].id=job-service-public-filter
spring.cloud.gateway.routes[2].uri=lb://job-service
spring.cloud.gateway.routes[2].order=-1
spring.cloud.gateway.routes[2].predicates[0]=Method=POST,OPTIONS
spring.cloud.gateway.routes[2].predicates[1]=Path=/api/jobs/filter

#Job-serive (Just only for recruiter)
spring.cloud.gateway.routes[3].id=job-service-secured
spring.cloud.gateway.routes[3].uri=lb://job-service
spring.cloud.gateway.routes[3].predicates[0]=Method=POST,PUT,DELETE
spring.cloud.gateway.routes[3].predicates[1]=Path=/api/jobs/**
# Name class apply must be end with GatewayFilterFactory
spring.cloud.gateway.routes[3].filters[0]=Authentication

spring.cloud.gateway.routes[4].id=application-service
spring.cloud.gateway.routes[4].uri=lb://application-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/applications/**
spring.cloud.gateway.routes[4].filters[0]=Authentication
