spring.application.name=spring-cloud-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=job-service
spring.cloud.gateway.routes[1].uri=lb://job-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/jobs/**
# Name class apply must be end with GatewayFilterFactory
spring.cloud.gateway.routes[1].filters[0]=Authentication 

spring.cloud.gateway.routes[2].id=application-service
spring.cloud.gateway.routes[2].uri=lb://application-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/applications/**
spring.cloud.gateway.routes[2].filters[0]=Authentication

app.jwt.secret=a4558b80-6594-4f4f-910b-1bc2ca62dfbf

