spring.application.name=spring-cloud-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#config allow cors front-end
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=1800

#config apply filter to multi-service

#Auth-service
spring.cloud.gateway.routes[0].id=auth-service-private
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].order=-1
spring.cloud.gateway.routes[0].predicates[0]=Method=GET
spring.cloud.gateway.routes[0].predicates[1]=Path=/api/auth/account
spring.cloud.gateway.routes[0].filters[0]=Authentication

spring.cloud.gateway.routes[1].id=auth-service-public
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**

#Job-service (Public for get jobs)
spring.cloud.gateway.routes[2].id=job-service-public-filter
spring.cloud.gateway.routes[2].uri=lb://job-service
spring.cloud.gateway.routes[2].order=-1
spring.cloud.gateway.routes[2].predicates[0]=Method=POST
spring.cloud.gateway.routes[2].predicates[1]=Path=/api/jobs/filter

spring.cloud.gateway.routes[3].id=job-service-public
spring.cloud.gateway.routes[3].uri=lb://job-service
spring.cloud.gateway.routes[3].order=-1
spring.cloud.gateway.routes[3].predicates[0]=Method=GET
spring.cloud.gateway.routes[3].predicates[1]=Path=/api/jobs/**
#optional
spring.cloud.gateway.routes[3].filters[0]=Authentication=true

spring.cloud.gateway.routes[4].id=job-service-private
spring.cloud.gateway.routes[4].uri=lb://job-service
spring.cloud.gateway.routes[4].order=-2
spring.cloud.gateway.routes[4].predicates[0]=Method=GET
spring.cloud.gateway.routes[4].predicates[1]=Path=/api/jobs/viewed, /api/jobs/saved, /api/jobs/{jobId}/is-saved
spring.cloud.gateway.routes[4].filters[0]=Authentication

# allow all request options pass
spring.cloud.gateway.routes[5].id=job-service-options
spring.cloud.gateway.routes[5].uri=lb://job-service
spring.cloud.gateway.routes[5].order=-1
spring.cloud.gateway.routes[5].predicates[0]=Method=OPTIONS
spring.cloud.gateway.routes[5].predicates[1]=Path=/api/jobs/**

#Job-serive (Just only for recruiter)
spring.cloud.gateway.routes[6].id=job-service-secured
spring.cloud.gateway.routes[6].uri=lb://job-service
spring.cloud.gateway.routes[6].predicates[0]=Method=POST,PUT,DELETE
spring.cloud.gateway.routes[6].predicates[1]=Path=/api/jobs/**
# Name class apply must be end with GatewayFilterFactory
spring.cloud.gateway.routes[6].filters[0]=Authentication

# Application-service
spring.cloud.gateway.routes[7].id=application-service-options
spring.cloud.gateway.routes[7].uri=lb://application-service
spring.cloud.gateway.routes[7].order=-1
spring.cloud.gateway.routes[7].predicates[0]=Method=OPTIONS
spring.cloud.gateway.routes[7].predicates[1]=Path=/api/applications/**

spring.cloud.gateway.routes[8].id=application-service
spring.cloud.gateway.routes[8].uri=lb://application-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/applications/**
spring.cloud.gateway.routes[8].filters[0]=Authentication

# Profile-service
spring.cloud.gateway.routes[9].id=profile-service-options
spring.cloud.gateway.routes[9].uri=lb://profile-service
spring.cloud.gateway.routes[9].order=-1
spring.cloud.gateway.routes[9].predicates[0]=Method=OPTIONS
spring.cloud.gateway.routes[9].predicates[1]=Path=/api/profile/**

spring.cloud.gateway.routes[10].id=profile-service
spring.cloud.gateway.routes[10].uri=lb://profile-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/profile/**
spring.cloud.gateway.routes[10].filters[0]=Authentication