version: '3.8'

services:
  eureka-server:
    build: 
      context: ./eureka-server 
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - recruitment-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  api-gateway:
    build:
      context: ./spring-cloud-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - recruitment-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - ALLOW_URL=${ALLOW_URL}
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    container_name: recruitment-rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - recruitment-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-db:
    image: mysql:8.0
    container_name: auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_service_db
    ports:
      - "3307:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - recruitment-network

  application-db:
    image: mysql:8.0
    container_name: application-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application_service_db 
    ports:
      - "3308:3306"
    volumes:
      - application_db_data:/var/lib/mysql
    networks:
      - recruitment-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6380:6379" 
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - recruitment-network

  matching-service:
    build:
      context: ./matching-service       
      dockerfile: Dockerfile
    container_name: matching-service
    ports:
      - "8000:8000"
    restart: always
    networks:
      - recruitment-network

  application-service:
    build: 
      context: ./application_service
      dockerfile: Dockerfile
    container_name: application-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=application-mysql
      - DB_PORT=3306 
      - DB_USER=root
      - DB_PASS=root
      - RABBITMQ_HOST=recruitment-rabbitmq
      - RABBITMQ_PORT=5672
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    depends_on:
      application-db:
        condition: service_started
      eureka-server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - recruitment-network
    restart: on-failure
    
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=auth-mysql
      - DB_PORT=3306 
      - DB_USER=root
      - DB_PASS=root
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - RABBITMQ_HOST=recruitment-rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - auth-db
      - eureka-server
    networks:
      - recruitment-network
    restart: on-failure

  job-service:
    build: 
      context: ./job-service
      dockerfile: Dockerfile
    container_name: job-service
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URI=${MONGODB_URI_JOB}
      - RABBITMQ_HOST=recruitment-rabbitmq
      - RABBITMQ_PORT=5672
      - BASE_URL_MATCHING_SERVICE=${BASE_URL_MATCHING_SERVICE}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    depends_on:
      eureka-server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - recruitment-network
    restart: on-failure

  profile-service:
    build: 
      context: ./profile-service
      dockerfile: Dockerfile
    container_name: profile-service
    ports:
      - "8084:8084"
    environment:
      - MONGODB_URI=${MONGODB_URI_PROFILE}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    depends_on:
      - eureka-server
    networks:
      - recruitment-network
    restart: on-failure

  blog-service:
    build: 
      context: ./blog_service
      dockerfile: Dockerfile
    container_name: blog-service
    ports:
      - "8085:8085"
    environment:
      - MONGODB_URI=${MONGODB_URI_BLOG}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - eureka-server
    networks:
      - recruitment-network
    restart: on-failure
  notification-service:
    build: 
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8086:8086"
    environment:
      - MONGODB_URI=${MONGODB_URI_NOTIFICATION}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - RABBITMQ_HOST=recruitment-rabbitmq
      - RABBITMQ_PORT=5672
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - EMAIL_SEND=${EMAIL_SEND}
      - URL_FE=${URL_FE}
    depends_on:
      - eureka-server
    networks:
      - recruitment-network
    restart: on-failure

  techroute-web:
    build: 
      context: ./techroute-web 
      dockerfile: Dockerfile
    container_name: techroute-web
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - recruitment-network

volumes:
  rabbitmq_data:
  redis_data:
  auth_db_data:
  application_db_data:

networks:
  recruitment-network:
    driver: bridge