const skills = [
    "Accounting",
    "AWS",
    "B2B Sales",
    "B2C Sales",
    "Banking Operations",
    "C#",
    "CI/CD",
    "Computer Vision",
    "Conflict Resolution",
    "Content Marketing",
    "CRM Software",
    "Customer Service",
    "Data Analysis",
    "Data Engineering",
    "Digital Marketing",
    "Docker",
    "Ecommerce Management",
    "Electronic Health Records (EHR)",
    "Embedded C",
    "Event Planning",
    "Figma",
    "Financial Analysis",
    "First Aid",
    "Food Safety (HACCP)",
    "Front Desk Management",
    "Git",
    "Google Analytics",
    "Hospitality Management",
    "HTML/CSS",
    "Inventory Management",
    "IoT Architecture",
    "Java Spring",
    "JavaScript",
    "Kubernetes",
    "Linux",
    "Machine Learning",
    "Magento",
    "Marketing",
    "Microsoft Excel",
    "MongoDB",
    "Multilingual",
    "Negotiation",
    "Node.js",
    "NoSQL",
    "Nursing",
    "Patient Care",
    "Pharmacology",
    "PHP",
    "POS Systems",
    "Python",
    "React",
    "Risk Management",
    "SEO/SEM",
    "Social Media Management",
    "SQL",
    "Technical Support",
    "TypeScript",
    "UI/UX Design"
  ];
  
  export default skills;