spring.application.name=discovery-server
server.port=8761

eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY:false}
